[package]
name = "lyre-core"
version.workspace = true
edition.workspace = true

[lib]
name = "lyre_core"
path = "src/lib.rs"

[dependencies]
uuid.workspace = true
rand.workspace = true
rayon.workspace = true
lofty.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
gstreamer.workspace = true
fnv.workspace = true

[dev-dependencies]
tempfile.workspace = true
